casaordenada/casaordenada/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
# The Net Ninja
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.auth.views import PasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path("accounts/password_reset/", PasswordResetView.as_view(template_name="usuarios/password_reset_form.html")),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += staticfiles_urlpatterns()
# else:
#     static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

casaordenada/usuarios/urls.py
from django.urls import path

from .views import test, index, signup, contact, correotest

app_name = 'usuarios'
urlpatterns = [
    # path('test/', test, name='test'),
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('accounts/signup/', signup, name='signup'),
    path('correotest/', correotest, name='correotest')
]

casaordenada/products/models.py
from django.db import models
import barcode
from barcode.writer import ImageWriter
from io import BytesIO
from django.core.files import File

class Product(models.Model):
    name = models.CharField(max_length=200)
    barcode = models.ImageField(upload_to='images/', blank=True, null=True)
    country_id = models.CharField(max_length=2, null=True)
    manufacturer_id = models.CharField(max_length=5, null=True)
    number_id = models.CharField(max_length=5, null=True)

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        EAN = barcode.get_barcode_class('ean13')
        ean = EAN(f'{self.country_id}{self.manufacturer_id}{self.number_id}', writer=ImageWriter())
        buffer = BytesIO()
        ean.write(buffer)
        self.barcode.save(self.name+'barcode.png', File(buffer), save=False )
        return super().save(*args, **kwargs)

casaordenada/usuarios/models.py
from django.db import models


class Usuario(models.Model):

	numero_id = models.CharField(max_length=50)
	tipo_documento = models.CharField(default="cédula", max_length=50)

casaordenada/usuarios/forms.py
from django import forms

# signup
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
	"""Form con email para el registro de usuarios"""
	email = forms.EmailField(required=True, label='email', error_messages={'exists': 'Este correo ya está en uso'})

	class Meta:
		model = User 
		fields = ('username', 'email', 'password1', 'password2')

	def save(self, commit=True):
		user = super(UserCreateForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

	def clean_email(self):
		if User.objects.filter(email=self.cleaned_data['email']).exists():
			raise forms.ValidationError(self.fields['email'].error_messages['exists'])
		return self.cleaned_data['email']


def should_be_empty(value):
	if value:
		raise forms.ValidationError('Bot ¬¬')
class ContactForm(forms.Form):
	"""Form de Contacto"""
	name = forms.CharField(max_length=80, widget=forms.TextInput(attrs={'class':'form-control'}))
	message = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	forcefield = forms.CharField(required=False, widget=forms.HiddenInput, label="leave empty", validators=[should_be_empty])

casaordenada/products/views.py
from django.shortcuts import render

# Create your views here.

casaordenada/usuarios/views.py
from django.shortcuts import render, redirect
# test
from django.http import HttpResponse
# signup
from django.contrib.auth import authenticate, login
from .forms import UserCreateForm
# contact
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError

# sendgrid
from django.conf import settings
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail


def test(request):

	return HttpResponse('<h1>successful</h1>')

def index(request):
	context={}
	return render(request, 'usuarios/index.html', context)

def signup(request):
	"""Signup - Victor Wooding"""
	if request.method == "POST":
		form = UserCreateForm(request.POST)
		print(form.errors)
		if form.is_valid():
			usuario_nuevo = form.save()
			usuario_nuevo = authenticate(
				username=form.cleaned_data['username'],
				password=form.cleaned_data['password1']
				)
			login(request, usuario_nuevo)
			return redirect('index')
	else:
		form = UserCreateForm()
	return render(request, 'registration/signup.html', {'form': form})



def contact(request):
	"""enviar email - Victor Wooding"""
	form = ContactForm()
	if request.method == "POST":
		form = ContactForm(request.POST)
		if form.is_valid():
			subject ="mensaje de {}".format(form.cleaned_data['name'])
			message = form.cleaned_data['message']
			sender = form.cleaned_data['email']
			recipients = ['jesusgilberdugo@gmail.com']
			try:
				send_mail(subject, message, sender, recipients, fail_silently=True)
			except BadHeaderError:
				return HttpResponse("invalid header found")
			return HttpResponse("success... message has been sent")		
	return render(request, 'usuarios/contact.html', {'form': form})

from django.core.mail import EmailMessage, send_mail, EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string, get_template


def enviar_correo(asunto, contenido, email_server, clientes):
	context = {
		'nombre': "Jesus",
		'contenido': contenido
	}
	contenido = render_to_string('correo.html', context)
	contenido = get_template('correo.html')
	contenido.render(context)
	## version 1
	# email = EmailMessage(asunto, contenido, email_server, clientes)
	# email.fail_silently=False
	# email.send()
	## version 2
	email = EmailMultiAlternatives(asunto, 'prueba', email_server, clientes) 
	email.attach_alternative(contenido, 'text/html')
	email.send()
	## version 3
	# send_mail(asunto, contenido, email_server, clientes)
	return None

def correotest(request):
	asunto = 'test 2 de octubre'
	contenido = 'masterproelite'
	email_server = settings.EMAIL_HOST_USER
	clientes = [settings.EMAIL_HOST_USER]
	enviar_correo(asunto, contenido, email_server, clientes)
	return HttpResponse('<h1>Correo Enviado</h2>')


# def contact_sendgrid(request):
# 	"""enviar email - documentación sendgrid"""
# 	form = ContactForm()
# 	if request.method == "POST":
# 		form = ContactForm(request.POST)
# 		if form.is_valid():
# 			message = Mail(
# 				from_email=form.cleaned_data['email'],
# 				to_emails='jesusgilberdugo@gmail.com',
# 				subject="mensaje de {}".format(form.cleaned_data['name']),
# 				html_content='<strong>{}</strong>'.format(form.cleaned_data['message']))
# 			try:
# 				sg = SendGridAPIClient(settings.SENDGRID_API_KEY) #os.environ.get('SENDGRID_API_KEY')
# 				response = sg.send(message)
# 				print(response.status_code)
# 				print(response.body)
# 				print(response.headers)
# 			except Exception as e:
# 				print(e)
# 			return HttpResponse("success... message has been sent")		
# 	return render(request, 'usuarios/contact.html', {'form': form})

casaordenada/usuarios/templates/base.html
 {% load static %}
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://bootswatch.com/4/pulse/bootstrap.min.css">
    <title>casa ordenada</title>
</head>
<body>
    <style>
        body{
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;

        }
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: #3398E1;
            color: white;
            text-align: center;
        }
        .shadow {
            box-shadow: 0 10px 50px -2px rgba(92, 225, 230, 0.2);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead{
            background: #3398E1;
            height: auto;
            padding-bottom: 10px;
            box-shadow: 0 16px 30px #E3E7EB;
            padding-top: 10px
        }
        .neomor{
            background: #ffffff;
            box-shadow:  5px 5px 10px -2px #d9d9d9,
            -20px -20px 20px #ffffff;     
        }               
    </style>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white mb-4 p-1 neomor">
  		<div class="container">

  			<a class="navbar-brand" href="/">
         <img src="{% static 'img/casa.png' %}" width="110" alt="" class="d-inline-block align-middle mr-2">       
            </a>

	  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	    	<span class="navbar-toggler-icon"></span>
	  		</button>
	  		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    	<div class="navbar-nav ml-auto">
                <a class="nav-item nav-link ml-1" href="{% url 'usuarios:contact' %}">contact</a>
	    		{% if user.is_authenticated %}
	      		<a class="nav-item nav-link ml-1" href="{% url 'logout' %}">logout</a>
	      		{% else %}
	      		<a class="nav-item nav-link ml-1" href="{% url 'login' %}">login</a>
	      		{% endif %}
	    	</div>
	  		</div>
  		</div>
  		
	</nav>

	<div class="container">
		{% block content %}
     	<!--Content Goes Here-->
        {% endblock content%}
        <a class="btn btn-primary" href="{% url 'usuarios:correotest' %}">ENVIAR CORREO</a>
	</div>
    


    <footer class="footer py-1 bg-dark">
        <p class="m-0 text-secondary text-center">Copyright &copy; Gilachus</p>
    </footer>
    
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

casaordenada/usuarios/templates/correo.html
<div style="background-color: bisque;">
    <p>Hola <strong>{{ nombre }}</strong> </p>

    <p>{{contenido}}</p>

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Vitae doloribus nulla cupiditate quam delectus nesciunt 
        dolorem aliquid quos sequi debitis ducimus iure tempore, minima adipisci maiores! 
        Minus dolorum alias ipsa.</p>
</div>

casaordenada/usuarios/templates/usuarios/contact.html
{% extends "base.html" %}

{% block content %}
	<h2>Deja tu mensaje</h2>
	<form method="POST">
		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
		{{ hidden }}
		{% endfor %}

		{% for field in form.visible_fields %}
		<div class="form-group">
			{{ field.errors }}
			<label>
				{{ field.label_tag}}
			</label>
			<p>{{ field }}</p>
		</div>
		{% endfor %}
		<button class="btn btn-secondary" type="reset">reset</button>
		<button class="btn btn-primary" type="submit">Enviar</button>
	</form>
{% endblock content %}

casaordenada/usuarios/templates/usuarios/index.html
{% extends 'base.html' %}

{% block content %}

	{% if user.is_authenticated %}
		<h2>welcome {{ user.username }}</h2> 
	{% else %}
	<div class="page-header">
		<h1 class="">DEJAMOS TU CASA ORDENADA</h1> 
		<p>Encuentra el servicio especializado de mantenimiento, reparaciones o aseo para tu hogar o empresa.</p>
	</div>
		
	{% endif%}
{% endblock %}

casaordenada/usuarios/templates/usuarios/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h2>Recuperar contraseña</h2>
<form action="." method="POST">
	{% csrf_token %}
	{% for field in form %}
	<div class="form-group">
		{{ field.errors }}
		<label class="m-0">{{ field.label_tag }}</label>
		<p>{{ field }}</p>
	</div>
	{% endfor %}
	<button type="submit" class="btn btn-primary">Enviar</button>
</form>
{% endblock %}